# Generated by Django 3.1.5 on 2021-03-29 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='NA', max_length=50)),
            ],
        ),
    ]
